name: Quickstart

on: workflow_dispatch
  #push:
  #  branches: main
  #pull_request:
  # branches: main
  #schedule:
  #  # run at noon every day
  #  - cron: "*/ * * * *"

defaults:
  # Required shell entrypoint to have properly activated conda environments
  run:
    shell: bash -l {0}

jobs:
  quickstart:
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false

    steps:
      # Needed to run on PR or branches 
      - name: Checkout source
        uses: actions/checkout@v2
          
      - name: Set up local environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          use-mamba: true
          environment-file: ci/environment-3.9.yaml

      - name: Run quickstart
        env:
          DASK_COILED__TOKEN: ${{ secrets.COILED_TOKEN }}
          #AWS_ACCESS_KEY_ID: ${{ secrets.BLOG_AWS_ACCESS_KEY_ID }}
          #AWS_SECRET_ACCESS_KEY: ${{ secrets.BLOG_AWS_SECRET_ACCESS_KEY }}
        run: python scripts/quickstart.py
